const cartTypes = {
    ADD_TO_CART : 'ADD_TO_CART',
    REDUCE_CART_ITEM: 'REDUCE_CART_ITEM',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    REMOVE_CART: 'REMOVE_CART',
    CLEAR_CART: 'CLEAR_CART'
}

export default cartTypes;