
const categoryTypes = {
    ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
    FETCH_CATEGORY: 'FETCH_CATEGORY',
    SET_CATEGORY: 'SET_CATEGORY',
    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    SET_CATEGORIES: 'SET_CATEGORIES',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    EDIT_CATEGORY: 'EDIT_CATEGORY',
}

export default categoryTypes;