const orderTypes = {
    ADD_TO_ORDER: 'ADD_TO_ORDER',

    FETCH_ORDERS: 'FETCH_ORDERS',
    SET_ORDERS: 'SET_ORDERS',


    GET_USER_ORDER_HISTORY: 'GET_USER_ORDER_HISTORY',
    SET_USER_ORDER_HISTORY: 'SET_USER_ORDER_HISTORY',

    GET_ORDER_DETAIL: 'GET_ORDER_DETAIL',
    SET_ORDER_DETAIL: 'SET_ORDER_DETAIL',


    DELETE_ORDER: 'DELETE_ORDER',
    EDIT_ORDER: 'EDIT_ORDER',

    
}

export default orderTypes;