const userTypes = {


    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
    SIGN_UP_USER_START: 'SIGN_UP_USER_START',
    USER_ERROR: 'USER_ERROR',
    FETCH_USER: 'FETCH_USER',
    SET_USERS: 'SET_USERS',
    DELETE_USER: 'DELETE_USER',
    FETCH_USER_ID: 'FETCH_USER_ID',
    SET_USER: 'SET_USER',
    EDIT_USER: 'EDIT_USER',
    ADD_NEW_USER: 'ADD_NEW_USER'


    , EDIT_USER_ADMIN: 'EDIT_USER_ADMIN',
    SET_USER_ADMIN: 'SET_USER_ADMIN',
    FETCH_USER_ADMIN: 'FETCH_USER_ADMIN',



    LOGIN_SUCCESS: 'LOGIN_SUCCESS',







};

export default userTypes;