

const productsTypes = {
    ADD_NEW_PRODUCT: 'ADD_NEW_PRODUCT',
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_HOME: 'FETCH_PRODUCTS_HOME',
    FETCH_PRODUCT_ID: 'FETCH_PRODUCT_ID',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_PRODUCTS_HOME: 'SET_PRODUCTS_HOME',
    SET_PRODUCT: 'SET_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    EDIT_PRODUCT: 'EDIT_PRODUCT',


    UPDATE_NUMBER: 'UPDATE_NUMBER',



    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',


    PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS'
}

export default productsTypes;